### ISSUE TITLE
Error with jvectormap when resize window

### ISSUE THREAD

**Issue by thaodx** [creativetimofficial/vue-paper-dashboard-pro#12]
Sometime, when i resize the browser window, this error shown on browser's console log:
https://i.imgur.com/nKYKSKe.png

`jquery-jvectormap.min.js?7b23:1 Error: <g> attribute transform: Expected number, "scale(NaN) translate(N…".`

**Comment by cristijora** [comment]
This error seems to be from jqvmap @alexandru-paduraru I also see this issue on the angular version. Do you have any fix for it? 
I was wondering if there is another alternative to make vector maps @alexandru-paduraru since I din't like jqvmap very much from the start but couldn't find something else which was open source and easy to work with.

**Comment by alexandru-paduraru** [comment]
@cristijora unfortunately, we don't have a fix for Angular either... I was looking for some answers in StackOverflow and found this: https://stackoverflow.com/questions/37277026/jvectormap-setfocus-error-jquery. We should try to add on `window.resize()` a method that will send also the scale value to the map. This is how I understand that the problem should be solved.

Changing the map with a vuejs native component is also a solution, but how you said, there isn't anything as good as jqvmap. So I think we should wait some time till we will have a good native component and trying to fix the issue with the resize.

Is this ok?

**Comment by locmai0808** [comment]
How did you guys solve this problem? I am still having this :( I'm using React Black Dashboard Pro

**Comment by Tekrajs** [comment]
@locmai0808 Me too.

**Comment by dragosct10** [comment]
Hi, @locmai0808! This is the repo for the vue paper dashboard pro product, not the Black Dashboard PRO React. I think the plugins are different between these two products. 

Regards,
Dragos
