### ISSUE TITLE
Vue Dash Pro - unexepected token issues

### ISSUE THREAD

**Issue by dilasciodev** [creativetimofficial/vue-paper-dashboard-pro#16]
Here are some screen grabs of the unexpected token issues I was seeing upon my first run locally of the vue paper pro version of the dashboard. I had no problem running the non-pro version
Thanks!!!

<img width="1280" alt="screen shot 2017-09-23 at 1 38 18 pm" src="https://user-images.githubusercontent.com/7550608/30775575-5ee58bba-a064-11e7-82c5-b531735a6982.png">
<img width="1280" alt="screen shot 2017-09-23 at 1 38 14 pm" src="https://user-images.githubusercontent.com/7550608/30775576-5ee95164-a064-11e7-9a10-71a31e8eb474.png">
<img width="1280" alt="screen shot 2017-09-23 at 1 38 10 pm" src="https://user-images.githubusercontent.com/7550608/30775574-5ee4c784-a064-11e7-8298-557cf8f37006.png">

**Comment by cristijora** [comment]
Hey @dilasciodev Could you also post `package.json` and `.babelrc` files? It seems like your a missing a babel plugin for latest javascript features.

**Comment by dilasciodev** [comment]
Cristi, thank you for the help. You were right i was missing a babel plugin. I found it and it worked. 
Thanks dude!!

**Comment by cristijora** [comment]
Glad I could help! 💪 Just a side question. Did you remove it somehow or was it missing? I know that it's included in the initial setup. `babel-preset-stage-2` ?

**Comment by dilasciodev** [comment]
I don't think I removed it. I tried fresh installs a couple times and that was what I was missing. As soon as I installed babel-preset-state thru npm it worked perfectly.  Maybe an issue with how I have things set up. I seem to be the only case of this.

**Comment by cristijora** [comment]
@dilasciodev My personal recommendation would be to use [yarn](https://yarnpkg.com/en/) It had more stable installations since I started using it. If you use yarn, then don't use it together with npm as they might have some conflicts. 

Also npm 5.0.x and npm 5.1.x had a couple of issues. Sometimes, when trying to install one dependency, for some reason npm removed all other dependencies. 

- Either upgrade to npm 5.4.x and use only npm
- Use only yarn to manage packages (`yarn add package-name` (dependencies), `yarn add -D package-name` (devDependencies))

**Comment by dilasciodev** [comment]
I think that may have been my issue. I have kind of been using both yarn and npm. I  appreciate the advice and will do that. Thanks for getting back so quick. I will definitely recommend your work to others. Thanks!

**Comment by jcorrego** [comment]
Hi, i have the same issue reported here. Just bought the pro version, unpack, and npm install, and fails because of eslint errors. First i dont understand why its shipped with eslint, if the code is not compatible... but anyway, i tried adding the ENABLE_ESLINT=false to dev and build scripts, but nothing...

running on latest npm: 5.5.1

I have removed node_modules several times, tried with yarn and npm and nothing

**Comment by cristijora** [comment]
Hi @jcorrego. Can you please tell me which version you downloaded (html or html + psd) and whether you have .babelrc file inside the source directory.

**Comment by cristijora** [comment]
A screenshot with the errors would also be very helpful :)

**Comment by jcorrego** [comment]
html + psd
yes, i have .babelrc:

`{
  "presets": ["es2015", "stage-2"],
  "plugins": ["transform-runtime",["component", [
    {
      "libraryName": "element-ui",
      "styleLibraryName": "theme-default"
    }
  ]]],
  "comments": false,
  "env": {
    "test": {
      "plugins": [ "istanbul" ]
    }
  }
}
`

**Comment by cristijora** [comment]
Is .babelrc in the source directory where package.json is? Someone had some issues because .babelrc was in another folder. 
Are these the errors from console or is this a screenshot? They don't seem very detailed. 
After changing ENABLE_ESLINT=false, `npm run dev` should be re run.

Sorry for a lot of questions. Trying to narrow down the issue

**Comment by cristijora** [comment]
If you want to do a really clean install right now I would recommend.
1. Deleting node_modules
2. Delete yarn.lock
3. yarn install

Or wtih npm
1. Delete node_modules
2. Delete package-lock.json
3. npm install

**Comment by cristijora** [comment]
Hm I suppose what the issue could be.
If you use node > 8, update node-sass package
```
yarn add -D node-sass
npm rebuild node-sass
```
When we released the first version of this theme, node-sass didn't support node 8 yet. Try updating that package and let me know

**Comment by jcorrego** [comment]
Yes @cristijora , `.babelrc` is in the same directory, just as it is after extracting the download.
That was a screenshot of the console output.

Like i said, i have added the ENABLE_ESLINT=false, and `npm run dev` and nothing changes. even removed again node_modules, run it again, but it appears that its ignoring that and still doing ESLINT

Removing node_modules and .lock files also didnt fix it.

node-sass was already in dependency packages, i run the  `npm rebuild node-sass` but  it didnt do anything...

**Comment by cristijora** [comment]
Please update node-sass dependency and npm rebuild node-sass then `npm run dev`

**Comment by jcorrego** [comment]
This is the complete output for `npm run dev`
```
> vue-paper-dashboard-pro@1.0.0 dev /Users/jcorrego/Desktop/LaunchMobility/adminportal
> cross-env node build/dev-server.js

(node:8048) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.


 ERROR  Failed to compile with 7 errors                                                                                                                                                           5:24:22 PM

 error  in ./src/App.vue

Syntax Error: Unexpected token (15:6)


 @ ./src/App.vue 7:2-97
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/Dashboard/Views/Charts.vue

Syntax Error: Unexpected token (176:8)


 @ ./src/components/Dashboard/Views/Charts.vue 7:2-109
 @ ./src/routes/routes.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/Dashboard/Views/Dashboard/Overview.vue

Syntax Error: Unexpected token (191:13)


 @ ./src/components/Dashboard/Views/Dashboard/Overview.vue 7:2-114
 @ ./src/routes/routes.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/Dashboard/Views/Maps/VectorMapsPage.vue

Syntax Error: Unexpected token (11:13)


 @ ./src/components/Dashboard/Views/Maps/VectorMapsPage.vue 7:2-120
 @ ./src/routes/routes.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/Dashboard/Views/Calendar/CalendarRoute.vue

Syntax Error: Unexpected token (12:13)


 @ ./src/components/Dashboard/Views/Calendar/CalendarRoute.vue 7:2-119
 @ ./src/routes/routes.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/UIComponents/SidebarPlugin/SideBar.vue

Syntax Error: Unexpected token (205:10)


 @ ./src/components/UIComponents/SidebarPlugin/SideBar.vue 7:2-110
 @ ./src/components/UIComponents/SidebarPlugin/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/UIComponents/Cards/ChartCard.vue

Syntax Error: Unexpected token (96:8)


 @ ./src/components/UIComponents/Cards/ChartCard.vue 7:2-112
 @ /Users/jcorrego/Desktop/~/buble-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/Dashboard/Views/Dashboard/Stats.vue
 @ ./src/components/Dashboard/Views/Dashboard/Stats.vue
 @ ./src/routes/routes.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

> Listening at http://localhost:8000
```

**Comment by jcorrego** [comment]
@cristijora What do you mean to update the node-sass dependency? its already installed at the latest version available: 4.5.3

Like  i said,  `npm rebuild node-sass` said everything is ok, and the error persists

**Comment by jcorrego** [comment]
@cristijora Should i start fixing ESLINT code syntax???? i dont understand how are you able to work with this configured this way...

BTW, your response times are great.

**Comment by jcorrego** [comment]
its working now, dont ask me what i did, just tried again, and worked.... hoping this wont be an issue when deploying or configuring another dev environment!
Thanks

**Comment by cristijora** [comment]
@jcorrego I meant simply updating the package. When downloaded it should have been 4.5.0 which is an older version that did not support node 8. 

Strangely I have not encountered such errors until now. Other people had issues only due to babelrc being placed in a wrong folder. Its a bit late here (0:30 am) 
I will continue to investigate tomorrow. Until then, I eould like to know:
1. Node version
2. Operating system
3. Maybe a copy of package.json (who knows maybe it got modified)

Regarding your eslint question, eslint is optional through that option. The fact that errors appear on the screen or console is because the vue cli setup is configured this way.
Really sorry that you have issues with it. Will do my best to see what went wrong there.

**Comment by cristijora** [comment]
Here are a couple of things I can advise for stability:
1 Dont mix yarn with npm for installing dependencies. They have different ways of installing packages and might causes issues. Use one of them (preferrably yarn as it ouputs better errors). Npm is ok to run tasks.
2. Dont use very new node versions (e.g node 9) since they are not stable and not all tools have stable integrations with the latest version of node.
3. If you need a clean install, delete node modules, yarn.lock or package-lock.json and reinstall

**Comment by cristijora** [comment]
@jcorrego Regarding deployment there is one gotcha which is more related to vue cli. Currently the dashboard cand be deployed as a static website pretty much eveywhere. If you will use vue router in history mode https://router.vuejs.org/en/essentials/history-mode.html , you will have to change 
`assetsPublicPath: ''` in config/index.js to `assetsPublicPath: '/`
